{% set name = "clyent" %}
{% set version = "1.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Anaconda-Platform/{{ name }}/archive/{{ version }}.tar.gz
  sha256: a4c33bd70fd3c53f133eb301db7b83acb7cbe6d1e405158b8f5582aa888d3aa3
  patches:
    - 0001-Remove-unused-module-imp-for-python-3.12-compatibili.patch
    - no_versioneer.py

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    # the python bound is probably lower than 3.6
    # but with conda-forge tooling of Nov 2023, I don't want
    # to let really old pythons install this
    - python >=3.8
    - setuptools
  run:
    - python >=3.8
    - setuptools

test:
  imports:
    - clyent

about:
  home: https://github.com/Anaconda-Platform/clyent
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Command line client library for windows and posix
  description: |
    Clyent is a python command line utility library for binstar,
    binstar-build, and chalmers.
  doc_url: https://pypi.python.org/pypi/clyent
  doc_source_url: https://github.com/Anaconda-Platform/clyent/blob/master/README.md
  dev_url: https://github.com/Anaconda-Platform/clyent

extra:
  recipe-maintainers:
    - nehaljwani
