travis:
  secure:
    BINSTAR_TOKEN: m2QenUQ9BD8CXO1fB6fOsk/lHGjKi7fEW44waiQ7nB+73gTX/DPo+SuCg5O3k27fkxVt/MA8kU69Sfm8GnPVI6g7mvJQ/89HlC7/nRI3sp47IxkNFJIqYb60rfIUkLaFw12yUVl7kjwggq5TRga4CHjn8ZBcXgaHrlW06ANztI1rBqaU1adhPa2goeuhpWnfzEjJ4Sr2LMY/5hApajeuZcqQC8kVMRZPWktW7x1mXMLzDKiq7zhJGLGm3utMp1iknR8fK7nwo8r4Kotl6Az6hv5/vKRuksn3akHP5D8vfrdawKEDrAnWrPIdbBfkH+AfyZVk6QCZVmhHtUmc4g1oyjZ+YOfaJr0G5uloSTAo2cR23Jcbp6gHdWWS3/wVqJspQMZDisJaLe7JPbe43oHZFrFrllhEZyPnmtsdhzSKEplDxfbOOb6TAsky94irCedG89aOd4CDg/2QHtXHyeoy1IsIpCzwe8fmP1XWcXz8MQqKO9C0K/NV19avz0naotWgCKBnLoBbrPV278squkACJzf152E32Dio12AEQV/AdtaxsxtRMNHAutJvsqjBJbR37npEEEpJQjEq0ywRCbouE20ZPAngZg/Ge2Cc9g6RSBx2E+isKeGItOgficHhMmtYy/IwgrEOk419uA3V4RWvzk4LANcO36SEIfK8jomloCE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
